### PR TITLE
Added some owl-individuals to knowrob-saphari for debugging.

### PR DESCRIPTION
**Pull request by airballking**
@daniel86 I tried to call the predicates we sketched, today. To this end, I added some owl-individuals for task, basket, slot, and slot-pose. 

Unfortunately, I get an error we querying for the slot-description:

`knowrob_saphari:saphari_slot_description(TaskID, SlotID, ToolClass, Pose)`

Error:

```
Caused by: jpl.PrologException: PrologException: error(existence_error(procedure, :(knowrob_saphari, /(current_time, 1))), context(:(knowrob_saphari, /(saphari_slot_pose, 3)), _16))
    at jpl.Query.get1(Query.java:336)
    at jpl.Query.hasMoreSolutions(Query.java:258)
    at jpl.Query.allSolutions(Query.java:556)
    at org.knowrob.json_prolog.query.AllSolutionsCommand.execute(AllSolutionsCommand.java:6)
    at org.knowrob.json_prolog.query.ThreadedQuery.run(ThreadedQuery.java:104)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
    at java.util.concurrent.FutureTask.run(FutureTask.java:262)
    ... 3 more
```

Could you please help me debug?

### CODE REVIEW

**Comment by airballking** [comment]
Update: I think I have found some tiny bugs, and narrowed down the problem. I no longer get an error when calling the predicate. Yeah! However, I also do not get any bindings:

``` prolog
knowrob_saphari:saphari_slot_description(T, SlotID, ToolClass, Pose).
```

--> no bindings

If I take the query apart I get bindings until this:

``` prolog
knowrob_saphari:saphari_active_task(T),
rdf_has(T, knowrob:objectActedOn, Basket),
rdf_has(SlotIdentifier, knowrob:physicalPartOf, Basket),
rdf_has(SlotIdentifier, knowrob:perceptionResponse, ObjectClass),
get_time(Time).
```

--> useful bindings

But this does not work:

``` prolog
knowrob_saphari:saphari_active_task(T),
rdf_has(T, knowrob:objectActedOn, Basket),
rdf_has(SlotIdentifier, knowrob:physicalPartOf, Basket),
rdf_has(SlotIdentifier, knowrob:perceptionResponse, ObjectClass),
get_time(Time),
knowrob_objects:object_pose_at_time(SlotIdentifier, Time, Pos, Quat).
```

--> no bindings

Any idea why prolog cannot find bindings for  `object_pose_at_time`?

EDIT: I got further down the rabbit hole, and it seems we cannot properly read out the actual pose values:

``` prolog
knowrob_saphari:saphari_active_task(T),
rdf_has(T, knowrob:objectActedOn, Basket),
rdf_has(SlotIdentifier, knowrob:physicalPartOf, Basket),
rdf_has(SlotIdentifier, knowrob:perceptionResponse, ObjectClass),
get_time(Time),
object_detection(SlotIdentifier, Time, Detection),
rdf_triple(knowrob:eventOccursAt, Detection, Pose).
```

--> useful bindings

``` prolog
knowrob_saphari:saphari_active_task(T),
rdf_has(T, knowrob:objectActedOn, Basket),
rdf_has(SlotIdentifier, knowrob:physicalPartOf, Basket),
rdf_has(SlotIdentifier, knowrob:perceptionResponse, ObjectClass),
get_time(Time),
object_detection(SlotIdentifier, Time, Detection),
rdf_triple(knowrob:eventOccursAt, Detection, Pose),
knowrob_objects:position_to_list(Pose, [X,Y,Z]).
```

--> no bindings

EDIT: This is as far as I could manage to track the error. Now, I'm at a loss. @daniel86 Do you see any reason for this to fail?

**Comment by daniel86** [comment]
I guess object_pose_at_time does not like that the transform is represented as translation/quaternion. You could try to use something like:

```
    <owl:NamedIndividual rdf:about="&knowrob;SemanticMapPerception_DFSFRWRE">
        <rdf:type rdf:resource="&knowrob;SemanticMapPerception"/>
        <knowrob:eventOccursAt rdf:resource="&pr2;RotationMatrix3D_OdUjB1wz"/>
        ........
    </owl:NamedIndividual>
    <owl:NamedIndividual rdf:about="&pr2;RotationMatrix3D_OdUjB1wz">
        <rdf:type rdf:resource="&knowrob;RotationMatrix3D"/>
        <knowrob:relativeTo rdf:resource="&pr2;RotationMatrix3D_DdX732rm"/>
        <knowrob:m00 rdf:datatype="&xsd;double">1.0</knowrob:m00>
        <knowrob:m01 rdf:datatype="&xsd;double">-0.0</knowrob:m01>
        <knowrob:m02 rdf:datatype="&xsd;double">0.0</knowrob:m02>
        <knowrob:m03 rdf:datatype="&xsd;double">0.0</knowrob:m03>
        <knowrob:m10 rdf:datatype="&xsd;double">0.0</knowrob:m10>
        <knowrob:m11 rdf:datatype="&xsd;double">1.0</knowrob:m11>
        <knowrob:m12 rdf:datatype="&xsd;double">-0.0</knowrob:m12>
        <knowrob:m13 rdf:datatype="&xsd;double">0.0</knowrob:m13>
        <knowrob:m20 rdf:datatype="&xsd;double">0.0</knowrob:m20>
        <knowrob:m21 rdf:datatype="&xsd;double">0.0</knowrob:m21>
        <knowrob:m22 rdf:datatype="&xsd;double">1.0</knowrob:m22>
        <knowrob:m23 rdf:datatype="&xsd;double">0.0</knowrob:m23>
        <knowrob:m30 rdf:datatype="&xsd;double">0.0</knowrob:m30>
        <knowrob:m31 rdf:datatype="&xsd;double">0.0</knowrob:m31>
        <knowrob:m32 rdf:datatype="&xsd;double">0.0</knowrob:m32>
        <knowrob:m33 rdf:datatype="&xsd;double">1.0</knowrob:m33>
    </owl:NamedIndividual>
```

I can have a look at support for quaternion/translation in that method tomorrow.

**Comment by daniel86** [comment]
I found the issue. individual names are not matching.
You used http://knowrob.org/kb/saphari.owl#Transformation_IAI_K42
As individual name for the transformation, but
http://knowrob.org/kb/saphari.owl#Transformation_IAI_K43
in the SemanticMapPerception event.

**Comment by airballking** [comment]
Oh, that type of bug... Sorry for not catching this myself, and thanks for finding it! :)

**Pull request merged**
